

kind: pipeline
type: docker
name: demo-nginx-release

environment:
  APP_CODE: 1000004
  APP_NAME: demo
  IMAGE_ARCH: amd64

steps:
  - name: 编译打包代码
    image: node:12.19.0-alpine
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'test echo'
      - npm config set registry https://registry.npm.taobao.org
      - cd  ./
      - npm install
      - npm run build
      - rm -rf node_modules


  - name: 构建镜像&PUSH镜像到Hub(UAT).
    image: plugins/docker
    settings:
      dockerfile: ./release/Dockerfile
      use_cache: true
      repo: ccr.ccs.tencentyun.com/windwithlife/demo
      registry: https://ccr.ccs.tencentyun.com/
      mirror: https://89cgb0wn.mirror.aliyuncs.com
      username: 100008098144
      password: password7&
      # 更多变量参考https://docs.drone.io/pipeline/environment/reference/
      tags:
        - ${DRONE_TAG=latest}
        - build-ci-${DRONE_BUILD_NUMBER}


  - name: 部署到K3S集群-(UAT)
    image: bh90210/dron8s:latest
    settings:
      yaml: ./release/deployment.yaml
      kubeconfig:
        from_secret: kubeconfig-zyq
      app_name: demo
      path_name: /demo
      image_name: ccr.ccs.tencentyun.com/windwithlife/demo
      soa_gateway: manager.zhangyongqiao.com
      soa_gateway_cert: admin-default-secret
      build_tag: build-ci-${DRONE_BUILD_NUMBER}

  - name: 注册镜像-发布记录
    image: centos
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'deployment....'
      - currentTime=`date +%Y%m%d%H%M%S`
      - buildNumber=Build$DRONE_BUILD_NUMBER-$currentTime

      - curl -H "Content-Type:application/json"
       -d '{"applicationCode":"'"$APP_CODE"'","imageName":"'"$APP_NAME"'","buildNumber":"'"$buildNumber"'","imageLabel":"'"$buildNumber"'"}'
       -X POST https://api.thingsminder.com/release-service/docker-image/registerDockerImage


      - curl -H "Content-Type:application/json"
       -d '{"applicationCode":"'"$APP_CODE"'","buildNumber":"'"$buildNumber"'"}'
       -X POST https://api.thingsminder.com/release-service/deployment/deployRecord

volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - release-nginx
  event:
    - push


---
kind: pipeline
type: docker
name: demo-zyq

environment:
  APP_CODE: 1000004
  APP_NAME: demo
  IMAGE_ARCH: amd64


steps:
  - name: 编译打包代码
    image: node:12.19.0-alpine
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'test echo'
      - npm config set registry https://registry.npm.taobao.org/
      - cd  ./
      - npm install
      - npm run build
      - rm -rf node_modules

  - name: 构建镜像&PUSH镜像到Hub.
    image: plugins/docker
    settings:
      dockerfile: ./release/DockerfileNode
      use_cache: true
      repo: ccr.ccs.tencentyun.com/windwithlife/demo
      registry: https://ccr.ccs.tencentyun.com
      mirror: https://89cgb0wn.mirror.aliyuncs.com
      username: 100008098144
      password: password7&
      # 更多变量参考https://docs.drone.io/pipeline/environment/reference/
      tags:
        - ${DRONE_TAG=latest}
        - build-ci-${DRONE_BUILD_NUMBER}

  - name: 部署到集群-dron8s方式(PROD)
    image: bh90210/dron8s:latest
    settings:
      yaml: ./release/deployment.yaml
      kubeconfig:
        from_secret: kubeconfig-zyq
      app_name: demo
      path_name: /demo
      image_name: ccr.ccs.tencentyun.com/windwithlife/demo
      soa_gateway: manager.zhangyongqiao.com
      soa_gateway_cert: admin-default-secret

      build_tag: build-ci-${DRONE_BUILD_NUMBER}

  - name: 注册镜像-发布记录
    image: centos
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'deployment....'
      - currentTime=`date +%Y%m%d%H%M%S`
      - buildNumber=Build$DRONE_BUILD_NUMBER-$currentTime

      - curl -H "Content-Type:application/json"
       -d '{"applicationCode":"'"$APP_CODE"'","imageName":"'"$APP_NAME"'","buildNumber":"'"$buildNumber"'","imageLabel":"'"$buildNumber"'"}'
       -X POST https://api.thingsminder.com/release-service/docker-image/registerDockerImage


      - curl -H "Content-Type:application/json"
       -d '{"applicationCode":"'"$APP_CODE"'","buildNumber":"'"$buildNumber"'"}'
       -X POST https://api.thingsminder.com/release-service/deployment/deployRecord


volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - release
  event:
    - push

