
kind: pipeline
type: docker
name: demo-PROD
environment:

  APP_CODE: 1000001
  APP_NAME: demo
  IMAGE_ARCH: amd64


steps:
  - name: 编译打包代码
    image: node:12.19.0-alpine
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'test miniprogram ci'
      - cd  ./
      - npm config set registry https://registry.npm.taobao.org/
      - npm install -g miniprogram-ci
      - npm install
      - npm run build:weapp
      - miniprogram-ci upload --pp ./ --pkp ./private.wx6df0275477ded21b.key --appid wx6df0275477ded21b --uv 1.0.${DRONE_BUILD_NUMBER} -r 1 --enable-es6 true
      - miniprogram-ci preview --pp ./ --pkp ./private.wx6df0275477ded21b.key --appid wx6df0275477ded21b --uv 1.1.${DRONE_BUILD_NUMBER} -r 1 --enable-es6 true --qrcode-format image  --qrcode-output-dest '/root/.m2/preview.jpg'

  - name: 上传体验版-发布记录
    image: centos
    volumes:
      - name : mvncache
        path : /root/.m2
    commands:
      - echo 'enter entos'
      - currentTime=`date +%Y%m%d%H%M%S`
      - buildNumber=Build$DRONE_BUILD_NUMBER-$currentTime

      - resultJson=$(curl -X POST -F "file=@/root/.m2/preview.jpg" https://api.thingsminder.com/common-service/media/uploadImage/windwithlife)
      # - echo $resultJson
      - qrImageUrl=$(echo $resultJson | sed 's/,/\n/g' | grep 'url' | sed 's/:/\n/' | sed '1d' | sed 's/"//g' | sed 's/}//g')
      - echo $qrImageUrl

      - curl -H "Content-Type:application/json"
       -d '{"installQR":"'"$qrImageUrl"'","applicationCode":"'"$APP_CODE"'","buildNumber":"'"$buildNumber"'"}'
       -X POST https://api.thingsminder.com/release-service/deployment/deployRecord


volumes:
  - name: mvncache
    host:
      path: /var/lib/cache/.m2

trigger:
  branch:
    - release
  event:
    - push
