# store your development credentials for spring app here
# this file should and will not be checked into version control
simple:
  domainName: thingsminder.com
  common:
    sentry-dsn: https://80bbf4ae778b525f9fe72e2813cd5246@sentry.io/1271087
  
 
  
  
